name: server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  common:
    path: ../common
  crypto: ^3.0.6
  cryptography: ^2.7.0
  dotenv: ^4.2.0
  meta: ^1.16.0
  postgres: ^3.5.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  test: ^1.25.5
